def clear_tables(conn):
    cursor = conn.cursor()
    cursor.execute('DELETE FROM label')
    cursor.execute('DELETE FROM text')
    cursor.execute('DELETE FROM language')
    cursor.execute('DELETE FROM text_source')
    cursor.execute('DELETE FROM schema')
    cursor.execute('DELETE FROM dataset')
    # cursor.execute('DROP TABLE post')
    # cursor.execute('DROP TABLE tweet')